Repository Dowongyeolui/molly-client, pull requests merged in 2025-03, with the labels that each got.

#46 fix: build 오류 수정
  src/views/buy/ui/BuyContainer.tsx
  src/views/cart/ui/OptionModal.tsx
  src/views/seller/components/ProductModify.tsx
  src/views/seller/components/ProductRegister.tsx
  src/views/seller/components/ProductRetriever.tsx
  src/views/seller/components/nav-projects.tsx
  src/views/seller/hooks/useImageUp.tsx
  src/views/seller/ui/SellerContainer.tsx
Labels: 🐞 BugFix

#52 test: fetchAPI 테스트 작성
  jest.config.ts
  jest.setup.ts
  src/features/cart/__test__/cartFetch.test.ts
  src/features/login/ui/LoginPage.tsx
  src/shared/__test__/fetch.test.ts
Labels: ✅ Test

#54 로그인 오류 수정
  app/page.tsx
  app/product/page.tsx
  jest.config.ts
  jest.setup.ts
  mocks/nextHeaders.ts
  src/features/cart/api/cartRead.ts
  src/features/cart/test/cartFetch.test.ts
  src/features/login/ui/LoginFormPage.tsx
  src/features/login/ui/LoginPage.tsx
  src/shared/util/lib/setCookie.ts
Labels: 🐞 BugFix, 🔨 Refactor

#55 Feat : 테스트 코드 작성
  app/product/page.tsx
  jest-mocks/fileMock.js
  jest.config.ts
  jest.setup.ts
  next.config.ts
  package.json
  public/main/GANNI.png
  public/main/ISSE.webp
  public/main/LA.webp
  public/main/LE.png
  public/main/MAISON.webp
  public/main/ami.png
  public/main/beanpole.webp
  public/main/dl.webp
  public/main/hmode.webp
  public/main/kuho.webp
  public/main/ssey.webp
  public/main/theory.webp
  public/main/uni.webp
  public/main/vun.webp
  public/main/메종.webp
  src/features/product/hooks/useProductList.tsx
  src/shared/types/product.ts
  src/shared/ui/style/style.css
  src/views/main/__test__/BannerSection.test.tsx
  src/views/main/__test__/BrandSection.test.tsx
  src/views/main/__test__/FeaturedBrandSection.test.tsx
  src/views/main/__test__/HotItemsSection.test.tsx
  src/views/main/__test__/PopularItemsSection.test.tsx
  src/views/main/__test__/StyleClipSection.test.tsx
  src/views/main/ui/BannerSection.tsx
  src/views/main/ui/BrandSection.tsx
  src/views/main/ui/CategoriesSection.tsx
  src/views/main/ui/FeaturedBrandSection.tsx
  src/views/main/ui/HotItemsSection.tsx
  src/views/main/ui/Main.tsx
  src/views/main/ui/PopularItemsSection.tsx
  src/views/main/ui/RecommendedItemsSection.tsx
  src/views/main/ui/StyleClipSection.tsx
  src/views/product/FilterSidebar.tsx
  src/views/product/SortModal.tsx
  src/views/product/ui/CategoryButtons.tsx
  src/views/product/ui/Product.tsx
  src/views/product/ui/ProductFilters.tsx
  src/views/product/ui/ProductList.tsx
  src/widgets/navbar/Navbar.tsx
  text.tsx
  yarn.lock
Labels: 🐞 BugFix, ✨ Feature

#59 fix: 장바구니 LCS 개선
  app/buy/page.tsx
  app/cart/page.tsx
  app/layout.tsx
  app/login/page.tsx
  app/mypage/layout.tsx
  app/page.tsx
  app/seller/layout.tsx
  src/features/buy/ui/BuyOrderButton.tsx
  src/features/product/hooks/useProductList.tsx
  src/views/buy/ui/BuyContainer.tsx
  src/views/buy/ui/BuySkeleton.tsx
  src/views/cart/ui/CartComponent.tsx
  src/views/cart/ui/CartProductInfo.tsx
  src/views/cart/ui/CartSkelton.tsx
  src/views/seller/api/registerProduct.ts
  src/views/seller/components/ProductRegister.tsx
  src/widgets/Footer.tsx
  src/widgets/navbar/Navbar.tsx
Labels: 🐞 BugFix

#62 장바구니 오류 수정
  app/buy/success/page.tsx
  app/detail/[productId]/page.tsx
  src/features/cart/api/cartDelete.ts
  src/features/detail/api/action.tsx
  src/features/detail/api/route.tsx
  src/features/detail/props.tsx
  src/views/buy/ui/BuyComplete.tsx
  src/views/buy/ui/BuyContainer.tsx
  src/views/cart/ui/CartComponent.tsx
  src/views/cart/ui/CartProductInfo.tsx
  src/views/detail/ui/detail.tsx
  src/views/mypage/ui/PointMyPage.tsx
  src/views/product/FilterSidebar.tsx
  src/views/product/SortModal.tsx
  src/widgets/navbar/Navbar.tsx
Labels: 🐞 BugFix

#63 fix: 빌드 에러 수정
  app/buy/success/page.tsx
  app/cart/page.tsx
  app/detail/[productId]/page.tsx
  public/logo.webp
  src/features/cart/api/cartDelete.ts
  src/features/cart/test/cartFetch.test.ts
  src/views/buy/ui/ProductImage.tsx
  src/views/cart/ui/CartProductInfo.tsx
Labels: 🐞 BugFix

#64 빌드 오류 수정
  app/detail/[productId]/page.tsx
  app/register/page.tsx
Labels: 🐞 BugFix

#65 빌드 오류 수정
  app/buy/success/page.tsx
  app/cart/page.tsx
  app/detail/[productId]/page.tsx
  app/page.tsx
  app/product/page.tsx
  app/register/page.tsx
  next.config.ts
  public/icons/alarm.svg
  public/icons/cart.svg
  public/icons/dot.svg
  public/icons/filter.svg
  public/icons/hamburger.svg
  public/icons/heart.svg
  public/icons/logout.svg
  public/icons/profile.svg
  public/icons/refresh.svg
  public/icons/search.svg
  public/images/accessories.svg
  public/images/bag.svg
  public/images/banner.webp
  public/images/brand.webp
  public/images/coat.svg
  public/images/default.webp
  public/images/fashion.svg
  public/images/kids.svg
  public/images/mustang.svg
  public/images/nylonJacket.svg
  public/images/product.svg
  public/images/review.jpg
  public/images/shoes.svg
  public/images/shortPadding.svg
  public/images/slider1-1.svg
  public/images/slider1-2.jpg
  public/images/slider1-3.jpg
  public/images/slider1.webp
  public/images/slider2.webp
  public/images/thumb.svg
  src/features/cart/api/cartDelete.ts
  src/features/cart/test/cartFetch.test.ts
  src/features/detail/api/action.tsx
  src/features/detail/api/route.tsx
  src/features/detail/props.tsx
  src/views/buy/ui/BuyContainer.tsx
  src/views/buy/ui/ProductImage.tsx
  src/views/cart/ui/CartComponent.tsx
  src/views/cart/ui/CartProductInfo.tsx
  src/views/detail/ui/detail.tsx
  src/views/main/ui/Main.tsx
  src/views/main/ui/RecommendedItemsSection.tsx
  src/views/mypage/ui/PointMyPage.tsx
  src/views/product/FilterSidebar.tsx
  src/views/product/ui/Product1.tsx
  src/views/product/ui/ProductList.tsx
  src/widgets/navbar/Navbar.tsx
  text.tsx
Labels: 🐞 BugFix

#66 fix: 빌드 에러 수정
  next.config.ts
  src/features/product/api/getProduct.ts
  src/shared/util/lib/fetchAPI.ts
  src/views/product/ui/Product1.tsx
Labels: 🐞 BugFix

#67 fix: 빌드 에러 수정
  src/features/product/api/getProduct.ts
Labels: 🐞 BugFix

#68 상품 페이지 페칭 오류 수정
  src/features/product/api/getProduct.ts
Labels: 🐞 BugFix

#69 chore : 토큰 에러 시 로그인 화면으로 이동하는 클라이언트 코드 삭제
  app/layout.tsx
  app/page.tsx
  src/features/detail/props.tsx
  src/shared/api/getProduct.ts
  src/views/detail/ui/ReviewModal.tsx
  src/views/detail/ui/detail.tsx
  src/views/main/ui/FeaturedBrandSection.tsx
  src/views/main/ui/HotItemsSection.tsx
  src/views/main/ui/Main.tsx
  src/views/main/ui/PopularItemsSection.tsx
  src/views/product/ui/Product1.tsx
Labels: 🔨 Refactor

#70 chore : 불필요한 코드 삭제
  src/app/provider/UrlStore.ts
  src/views/detail/ui/detail.tsx
  src/views/main/ui/FeaturedBrandSection.tsx
  src/views/product/ui/Product1.tsx
Labels: 🔨 Refactor

#72 빌드 오류 수정
  app/api/login/route.ts
  app/api/loginStatus/route.ts
  app/api/logout/route.ts
  app/seller/layout.tsx
  middleware.ts
  next.config.ts
  src/app/provider/UrlStore.ts
  src/features/detail/api/action.tsx
  src/features/login/api/loginStatus.ts
  src/features/login/api/logout.ts
  src/features/mypage/api/orderRetriever.ts
  src/views/main/ui/FeaturedBrandSection.tsx
  src/views/main/ui/PopularItemsSection.tsx
  src/views/mypage/ui/ProductList.tsx
  src/views/mypage/ui/ProfileMyPage.tsx
  src/views/product/ui/Product1.tsx
  src/views/seller/api/updateProduct.ts
  src/views/seller/components/ProductModify.tsx
  src/views/seller/components/ProductRegister.tsx
  src/views/seller/components/ProductRetriever.tsx
  src/widgets/navbar/Navbar.tsx
  src/widgets/navbar/ProfileModal.tsx
Labels: 🐞 BugFix, 🌏 Deploy

#73 fix: 빌드 에러 수정
  app/api/login/route.ts
  app/api/loginStatus/route.ts
  app/api/logout/route.ts
  app/layout.tsx
  app/page.tsx
  app/seller/layout.tsx
  middleware.ts
  next.config.ts
  src/app/provider/Sellerstore.ts
  src/app/provider/UrlStore.ts
  src/features/cart/api/cartUpdate.ts
  src/features/detail/api/action.tsx
  src/features/detail/props.tsx
  src/features/login/api/loginStatus.ts
  src/features/login/api/logout.ts
  src/features/login/ui/LoginPage.tsx
  src/features/mypage/api/orderRetriever.ts
  src/shared/api/getProduct.ts
  src/views/cart/ui/ItemDuplicate.tsx
  src/views/detail/ui/ReviewModal.tsx
  src/views/detail/ui/detail.tsx
  src/views/main/ui/FeaturedBrandSection.tsx
  src/views/main/ui/HotItemsSection.tsx
  src/views/main/ui/Main.tsx
  src/views/main/ui/PopularItemsSection.tsx
  src/views/mypage/ui/ProductList.tsx
  src/views/mypage/ui/ProfileMyPage.tsx
  src/views/product/ui/Product1.tsx
  src/views/seller/api/batchProduct.ts
  src/views/seller/api/retrieverProduct.ts
  src/views/seller/api/updateProduct.ts
  src/views/seller/components/ProductBatch.tsx
  src/views/seller/components/ProductModify.tsx
  src/views/seller/components/ProductRegister.tsx
  src/views/seller/components/ProductRetriever.tsx
  src/views/seller/components/app-sidebar.tsx
  src/views/seller/components/nav-main.tsx
  src/views/seller/ui/SellerContainer.tsx
  src/views/seller/ui/sidebar.tsx
  src/widgets/navbar/Navbar.tsx
  src/widgets/navbar/ProfileModal.tsx
Labels: 🐞 BugFix, 🌏 Deploy

#75 Dev
  app/trend/page.tsx
  public/main/GANNI.png
  public/main/ISSE.webp
  public/main/LE.png
  public/main/MaisonKitsune.webp
  public/main/athe.avif
  public/main/beanpole.webp
  public/main/dl.webp
  public/main/dust.avif
  public/main/hmode.webp
  public/main/ilco.avif
  public/main/keen.avif
  public/main/lacoste.webp
  public/main/ssey.webp
  public/main/theory.webp
  public/main/tngt.avif
  public/main/vun.webp
  public/main/메종.webp
  src/app/provider/UrlStore.ts
  src/views/main/ui/BrandSection.tsx
  src/views/main/ui/FeaturedBrandSection.tsx
  src/views/main/ui/HotItemsSection.tsx
  src/views/main/ui/Main.tsx
  src/views/main/ui/PopularItemsSection.tsx
  src/views/main/ui/StyleClipSection.tsx
  src/views/mypage/ui/ProfileMyPage.tsx
  src/views/product/FilterSidebar.tsx
  src/views/product/SortModal.tsx
  src/views/product/ui/Product1.tsx
  src/views/trend/ui/trend.tsx
  src/widgets/navbar/Navbar.tsx
Labels: 🐞 BugFix, 🌏 Deploy

#76 Fix: 스타일 및 빌드 에러 수정
  app/layout.tsx
  public/main/Maison.svg
  public/main/ami.png
  public/main/athe.avif
  public/main/athe.png
  public/main/dust.png
  public/main/ilco.avif
  public/main/ilco.png
  public/main/keen-1.svg
  public/main/logo-ami.png
  public/main/tngt.avif
  public/main/tngt.png
  src/app/provider/UrlStore.ts
  src/views/detail/ui/CartToast.tsx
  src/views/detail/ui/detail.tsx
  src/views/main/ui/BrandSection.tsx
  src/views/main/ui/FeaturedBrandSection.tsx
  src/views/main/ui/HotItemsSection.tsx
  src/views/main/ui/Main.tsx
  src/views/main/ui/PopularItemsSection.tsx
  src/views/main/ui/RecommendedItemsSection.tsx
  src/views/product/FilterSidebar.tsx
  src/views/product/ui/Product1.tsx
  src/views/trend/ui/trend.tsx
  src/widgets/navbar/Navbar.tsx
Labels: 🐞 BugFix, 🌏 Deploy

#77 주문생성 오류 수정
  src/features/cart/api/cartOrder.ts
  src/features/cart/hooks/useCartItems.tsx
  src/features/cart/hooks/useCartOptions.ts
  src/features/cart/hooks/useDeleteItem.tsx
  src/features/cart/hooks/useDeleteSelected.tsx
  src/features/cart/hooks/useOrderCart.tsx
  src/features/cart/hooks/useSelected.tsx
  src/features/cart/hooks/useSelectedAll.tsx
  src/features/detail/api/action.tsx
  src/views/cart/test/cartComponent.test.ts
  src/views/cart/ui/CartComponent.tsx
  src/views/cart/ui/OptionModal.tsx
Labels: 🐞 BugFix, 🌏 Deploy

#80 빌드 오류 수정
  next.config.ts
  package.json
  src/views/address/ui/AddressContainer.tsx
  src/views/product/ui/Product1.tsx
  src/widgets/navbar/Navbar.tsx
Labels: 🐞 BugFix, 🌏 Deploy

#82 navbar css 수정
  src/widgets/Footer.tsx
  src/widgets/navbar/Navbar.tsx
  tailwind.config.ts
  tsconfig.json
Labels: 🐞 BugFix

#83 navbar css 수정
  src/widgets/Footer.tsx
  src/widgets/navbar/Navbar.tsx
  tailwind.config.ts
  tsconfig.json
Labels: 🐞 BugFix

#85 fix: next.config 설정수정
  next.config.ts
Labels: 🌏 Deploy

#86 fix: config 설정수정
  next.config.ts
Labels: 🌏 Deploy

#87 fix: 이미지 최적화 수정
  src/views/buy/ui/ProductImage.tsx
Labels: 🐞 BugFix, 🌏 Deploy

#88 fix: 이미지 최적화 수정
  src/views/cart/ui/OptionModal.tsx
  src/views/detail/ui/CartToast.tsx
  src/views/detail/ui/ReviewModal.tsx
  src/views/detail/ui/detail.tsx
  src/views/main/ui/BannerSection.tsx
  src/views/main/ui/BrandSection.tsx
  src/views/main/ui/FeaturedBrandSection.tsx
  src/views/main/ui/HotItemsSection.tsx
  src/views/main/ui/PopularItemsSection.tsx
  src/views/main/ui/RecommendedItemsSection.tsx
  src/views/main/ui/StyleClipSection.tsx
  src/views/mypage/ui/MypageOrderDetail.tsx
  src/views/mypage/ui/ProductList.tsx
  src/views/product/ui/Product1.tsx
  src/views/product/ui/ProductList.tsx
  src/views/review/ui/postModal.tsx
  src/views/seller/components/ProductRegister.tsx
  src/views/seller/components/ProductRetriever.tsx
  src/views/trend/ui/trend.tsx
  src/widgets/navbar/NotificationSidebar.tsx
Labels: 🐞 BugFix, 🌏 Deploy

#89 회원가입 오류 수정
  app/register/page.tsx
  next.config.ts
  src/features/buy/ui/BuyOrderButton.tsx
  src/features/register/api/registerPost.ts
  src/features/register/ui/RegisterContain.tsx
  src/shared/api/getProduct.ts
  src/views/buy/ui/ProductImage.tsx
  src/views/cart/api/formatPrice.ts
  src/views/cart/ui/CartOrderButton.tsx
  src/views/cart/ui/CartProductInfo.tsx
  src/views/cart/ui/OptionModal.tsx
  src/views/detail/ui/CartToast.tsx
  src/views/detail/ui/ReviewModal.tsx
  src/views/detail/ui/detail.tsx
  src/views/main/ui/BannerSection.tsx
  src/views/main/ui/BrandSection.tsx
  src/views/main/ui/FeaturedBrandSection.tsx
  src/views/main/ui/HotItemsSection.tsx
  src/views/main/ui/PopularItemsSection.tsx
  src/views/main/ui/RecommendedItemsSection.tsx
  src/views/main/ui/StyleClipSection.tsx
  src/views/mypage/ui/MypageOrderDetail.tsx
  src/views/mypage/ui/ProductList.tsx
  src/views/product/ui/Product1.tsx
  src/views/product/ui/ProductList.tsx
  src/views/review/ui/postModal.tsx
  src/views/seller/api/retrieverProduct.ts
  src/views/seller/components/ProductRegister.tsx
  src/views/seller/components/ProductRetriever.tsx
  src/views/trend/ui/trend.tsx
  src/widgets/navbar/Navbar.tsx
  src/widgets/navbar/NotificationSidebar.tsx
Labels: 🐞 BugFix

#91 fix: 이미지 최적화 수정
  src/views/buy/ui/ProductImage.tsx
  src/views/mypage/ui/ProductList.tsx
Labels: 🐞 BugFix, 🌏 Deploy

#92 Fix : 이미지 리사이징 요청
  src/views/detail/ui/ProductRecommend.tsx
  src/views/detail/ui/ProductReview.tsx
  src/views/detail/ui/ReviewModal.tsx
  src/views/detail/ui/detail.tsx
  src/views/main/ui/FeaturedBrandSection.tsx
  src/views/main/ui/HotItemsSection.tsx
  src/views/main/ui/PopularItemsSection.tsx
  src/views/main/ui/StyleClipSection.tsx
  src/views/product/ui/Product1.tsx
  src/views/trend/ui/trend.tsx
Labels: 🐞 BugFix

#93 Dev : 이미지 리사이징
  src/views/buy/ui/ProductImage.tsx
  src/views/detail/ui/ProductRecommend.tsx
  src/views/detail/ui/ProductReview.tsx
  src/views/detail/ui/ReviewModal.tsx
  src/views/detail/ui/detail.tsx
  src/views/main/ui/FeaturedBrandSection.tsx
  src/views/main/ui/HotItemsSection.tsx
  src/views/main/ui/PopularItemsSection.tsx
  src/views/main/ui/StyleClipSection.tsx
  src/views/mypage/ui/ProductList.tsx
  src/views/product/ui/Product1.tsx
  src/views/trend/ui/trend.tsx
Labels: 🐞 BugFix

#94 빌드 오류 수정
  app/layout.tsx
  app/page.tsx
  package.json
  src/features/buy/api/tossRequest.ts
  src/features/buy/ui/PaymentProcessor.tsx
  src/views/buy/ui/BuyComplete.tsx
  src/views/cart/ui/OptionModal.tsx
  yarn.lock
Labels: 🌏 Deploy

#95 빌드 오류 수정
  app/layout.tsx
  app/page.tsx
  package.json
  src/features/buy/api/tossRequest.ts
  src/features/buy/ui/PaymentProcessor.tsx
  src/views/buy/ui/BuyComplete.tsx
  src/views/cart/ui/OptionModal.tsx
  yarn.lock
Labels: 🌏 Deploy

#96 빌드 오류 수정
  app/layout.tsx
Labels: 🌏 Deploy

#97 Fix : 스켈레톤 UI 렌더링 버그 수정
  app/detail/[productId]/page.tsx
  app/product/page.tsx
  public/main/MaisonKitsune.webp
  public/main/dust.avif
  public/main/keen.avif
  src/views/detail/ui/ProductRecommend.tsx
  src/views/detail/ui/ProductReview.tsx
  src/views/detail/ui/ReviewModal.tsx
  src/views/detail/ui/detail.tsx
  src/views/main/ui/BrandSection.tsx
  src/views/main/ui/FeaturedBrandSection.tsx
  src/views/main/ui/HotItemsSection.tsx
  src/views/main/ui/Main.tsx
  src/views/main/ui/PopularItemsSection.tsx
  src/views/main/ui/StyleClipSection.tsx
  src/views/product/ui/CategoryButtons.tsx
  src/views/product/ui/LoadingSkeleton.tsx
  src/views/product/ui/Product.tsx
  src/views/product/ui/Product1.tsx
  src/views/product/ui/ProductList.tsx
  src/views/product/ui/SortButtons.tsx
  src/widgets/Footer.tsx
Labels: 🐞 BugFix

#98 feat: 검색 및 프로필 버튼에 aria-label 추가 및 키보드 접근성 강화
  src/views/product/ui/Product.tsx
  src/widgets/navbar/Navbar.tsx
Labels: ✨ Feature

#100 빌드 오류 수정
  app/layout.tsx
  src/features/address/api/addressDefault.ts
  src/features/buy/api/tossRequest.ts
  src/features/buy/ui/PaymentProcessor.tsx
  src/features/register/api/registerPost.ts
  src/features/register/hook/useRegisterForm.ts
  src/features/register/hook/useTermsAgreement.ts
  src/features/register/ui/RegisterContain.tsx
  src/views/buy/ui/Buy.tsx
  src/views/buy/ui/BuyComplete.tsx
  src/views/buy/ui/BuyContainer.tsx
  src/views/cart/ui/Cart.tsx
  src/views/cart/ui/CartComponent.tsx
  src/views/cart/ui/CartProductInfo.tsx
  src/views/cart/ui/CartSkelton.tsx
  src/views/mypage/ui/ProductList.tsx
  src/views/product/ui/Product1.tsx
  src/views/seller/components/ProductRetriever.tsx
Labels: 🐞 BugFix, 🌏 Deploy

#101 컴포넌트 구조 수정
  src/features/register/api/registerPost.ts
Labels: 🐞 BugFix, 🌏 Deploy, 🔨 Refactor

#102 CartNotice 수정
  src/views/cart/ui/Cart.tsx
  src/views/cart/ui/CartNotice.tsx
Labels: 🔨 Refactor

#103 CartNotice 수정
  src/views/cart/ui/Cart.tsx
  src/views/cart/ui/CartNotice.tsx
Labels: 🔨 Refactor

#104 브라우저 히스토리 추가
  middleware.ts
  src/features/login/ui/LoginFormPage.tsx
Labels: ✨ Feature, 🔨 Refactor

#105 로그인 자동 포커스
  app/not-found.tsx
  src/features/login/ui/LoginPage.tsx
  src/shared/api/getProduct.ts
  src/views/main/ui/RecommendedItemsSection.tsx
  src/views/mypage/ui/ProductList.tsx
  src/views/product/ui/Product.tsx
Labels: 🐞 BugFix, 🌏 Deploy, ✨ Feature

#106 로그인 포커스 설정
  app/not-found.tsx
  middleware.ts
  src/features/login/ui/LoginFormPage.tsx
  src/features/login/ui/LoginPage.tsx
  src/shared/api/getProduct.ts
  src/views/main/ui/HotItemsSection.tsx
  src/views/main/ui/PopularItemsSection.tsx
  src/views/main/ui/RecommendedItemsSection.tsx
  src/views/mypage/ui/ProductList.tsx
  src/views/product/ui/Product.tsx
  src/views/product/ui/Product1.tsx
  src/widgets/Footer.tsx
  src/widgets/navbar/Navbar.tsx
Labels: 🐞 BugFix, 🌏 Deploy, ✨ Feature
